### ISSUE TITLE
AdMobBanner crashes when switching tasks.

### ISSUE THREAD

**Issue by tom-hines** [FalsinSoft/QtAndroidTools#2] opened 2019-03-12 19:01 UTC
Hello and thank you for this great software.  AdMobBanner crashes when switching tasks.  To reproduce:

1. Start QtAndroidToolsDemo
2. Select AdMobBanner menu
3. Click "SHOW BANNERS" button.
4. Switch to another task from the Android task selector.
```
The following stack trace is printed:
F art     : art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception java.lang.IllegalStateException: pause must be called on the main UI thread.
F art     : art/runtime/java_vm_ext.cc:410]   at void uv.a(java.lang.String) (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):11)
F art     : art/runtime/java_vm_ext.cc:410]   at void com.google.android.gms.ads.nonagon.shim.k.w() (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):88)
F art     : art/runtime/java_vm_ext.cc:410]   at void com.google.android.gms.ads.nonagon.shim.m.w() (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):43)
F art     : art/runtime/java_vm_ext.cc:410]   at boolean com.google.android.gms.ads.internal.client.al.a(int, android.os.Parcel, android.os.Parcel) (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):194)
F art     : art/runtime/java_vm_ext.cc:410]   at boolean na.onTransact(int, android.os.Parcel, android.os.Parcel, int) (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):10)
F art     : art/runtime/java_vm_ext.cc:410]   at boolean android.os.Binder.transact(int, android.os.Parcel, android.os.Parcel, int) (Binder.java:387)
F art     : art/runtime/java_vm_ext.cc:410]   at void com.google.android.gms.internal.ads.zzej.transactAndReadExceptionReturnVoid(int, android.os.Parcel) ((null):-1)
F art     : art/runtime/java_vm_ext.cc:410]   at void com.google.android.gms.internal.ads.zzku.pause() ((null):-1)
F art     : art/runtime/java_vm_ext.cc:410]   at void com.google.android.gms.internal.ads.zzly.pause() ((null):-1)
F art     : art/runtime/java_vm_ext.cc:410]   at void com.google.android.gms.ads.BaseAdView.pause() ((null):-1)
F art     : art/runtime/java_vm_ext.cc:410]   at void com.google.android.gms.ads.AdView.pause() ((null):-1)
F art     : art/runtime/java_vm_ext.cc:410]   at void com.falsinsoft.qtandroidtools.AndroidAdMobBanner.appStateChanged(int) (AndroidAdMobBanner.java:197)
```
The problem seems to be in the function appStateChanged in AndroidAdMobBanner.java.  Seems the calls to  mBannerView.pause() and  mBannerView.resume() need to be wrapped in SyncRunOnUiThread to run on the UI thread.

My environment:
QtAndroidTools-0.8
Qt 5.12
Android 8.0 (API 26)

**Comment by FalsinSoft** [comment] 2019-03-12 20:21
Hi tom-hines
I reallyt thank you for the report. After a quick test I confirmed the problem was in the incorrect call of pause/resume as you indicated. I just committed a fixed version. Please, if you can, try it too and confirm the problem disappeared for close the issue.

**Comment by tom-hines** [comment] 2019-03-12 20:44
That fixed it.  Tested on both x86 emulator and armv7 Moto G5 phone.  Thank you!

**Comment by FalsinSoft** [comment] 2019-03-12 20:47
Thanks to you for the very detailed report ^_^

**Closed as completed** 2019-03-12 20:51 UTC
