### ISSUE TITLE
copy aidl Error

### ISSUE THREAD

**Issue by ismailGz** [FalsinSoft/QtAndroidTools#1] opened 2019-02-11 14:53 UTC
Hi,
Firstly thanks for this project but I have an issue. When I try to compile the project, I get this error from compiler:
error: [copy_aidl] Error 2

I also tried with demo project but result is same. What is reason of this problem?

**Comment by FalsinSoft** [comment] 2019-02-11 15:24
Hi
I just tested again the demo project and it work as expected, no error happened. I'm testing using Qt Creator latest version 4.8.1 under Windows 10. May I know your environment?

**Comment by ismailGz** [comment] 2019-02-11 15:28
My environment:
Qt Version: 5.11
Qt Creator Version: 4.8.1
OS: MacOS High Sierra

**Comment by FalsinSoft** [comment] 2019-02-11 15:40
Unfortunately I'm unable to verify under your environment cause I don't have a mac. In any case the "copy_aidl" label is the additional command instruct the cmake to check if the folder $$ANDROID_PACKAGE_SOURCE_DIR/aidl/com/android/vending/licensing exist and, if not, copy it from the library folder. You can try to manually copy the two folders "src" and "aidl" from QtAndroidTools folder to your android app folder and check if compilation go on. This workaround will work but is possible the compiler still show the same error. In this case comment out the following lines in the QtAndroidTools.pri file:

```
copy_src.commands = $(CHK_DIR_EXISTS) $$shell_path($$ANDROID_PACKAGE_SOURCE_DIR/src/com/falsinsoft/qtandroidtools) $(COPY_DIR) $$shell_path($$PWD/src) $$shell_path($$ANDROID_PACKAGE_SOURCE_DIR/src)
copy_aidl.commands = $(CHK_DIR_EXISTS) $$shell_path($$ANDROID_PACKAGE_SOURCE_DIR/aidl/com/android/vending/licensing) $(COPY_DIR) $$shell_path($$PWD/aidl) $$shell_path($$ANDROID_PACKAGE_SOURCE_DIR/aidl)
PRE_TARGETDEPS += copy_src copy_aidl
QMAKE_EXTRA_TARGETS += copy_src copy_aidl

```
Keep me informed about the result.

**Comment by ismailGz** [comment] 2019-02-11 19:56
I did what you say about aidl and error is gone. However another error occurred for Images.java file in this line:
`cur = getContentResolver().query.....`

I deleted these lines from Images java file. Finally, my project is compiled properly and worked. :) But demo project still gives following error in deploy stage. 

adb: error: cannot stat '/Users/ismail/Desktop/QtAndroidTools-master/build-QtAndroidToolsDemo-Android_for_armeabi_v7a_Clang_Qt_5_11_1_for_Android_armv72-Debug/android-build//build/outputs/apk/android-build-debug.apk': No such file or directory
22:19:25: The process "/Users/ismail/Qt/5.11.1/android_armv7/bin/androiddeployqt" exited with code 16.

Also, I used AdBanner in my project without any problem but when I used my own unitId instead of test id, I'm getting Error 0.

**Comment by FalsinSoft** [comment] 2019-02-11 20:18
At first remember for your app you have to use the last tagged stable version, not the last commit in the master branch cause is still in developing and is not stable. Regarding abd error I really don't know. I use this library in my apps too with adbanner and it work as expected. I'll try to find a mac inside a virtual machine and test the library for reproduce and fix these issues...

**Comment by ismailGz** [comment] 2019-02-12 10:33
Thank you for your help. If I will solve the problems, I will communicate with you.

**Comment by edips** [comment] 2019-04-01 20:57
Thanks for the project. I had the same error on Linux (Manjaro),I copied java files manually, but then I got very long error lists about java files (adnob, google's download.java etc) I only needed permissions, so I deleted all java codes and other modules from pri file, permissions worked with qml.

**Comment by FalsinSoft** [comment] 2019-04-03 06:23
Hi
Regarding error on Linux I'll investigate. In case you need only one tool of the library you don't need to modify the library .pri file but you just have to specify in your project .pro file the labels of the tools you want to use as follow (in case of permission only as your need):
```
DEFINES += \
    QTAT_APP_PERMISSIONS
include(../QtAndroidTools/QtAndroidTools.pri)
```
This will exclude all other tools code from be copyed or compiled.

**Comment by edips** [comment] 2019-04-03 11:26
Yes I did the same in pro file. It is working :)

**Comment by FalsinSoft** [comment] 2019-04-12 14:14
Hi all
Just pushed a change that should fix this compilation problem on Linux and MacOS (I tested in Linux only cause I don't have a mac). Please, try to update to latest verision and check if the problem is fixed for both (and keep me informed ^_^).
Thank you

**Comment by ismailGz** [comment] 2019-04-14 15:27
Hi,
I tried latest version on macOS High Sierra and it's compiled without any problem. Thank you.

**Comment by FalsinSoft** [comment] 2019-04-14 16:10
Thank you for your help.
I'll close this issue

**Closed as completed by FalsinSoft** 2019-04-14 16:10 UTC
