### ISSUE TITLE
java.lang.NullPointerException again

### ISSUE THREAD

**Issue by FranckRICHARD01** [FalsinSoft/QtAndroidTools#22] opened 2020-08-08 10:24 UTC
Hello,

I have again crashes java.lang.NullPointerException which seem to appear when the apk file associated with my application is downloaded:

java.lang.NullPointerException: 
  at javax.crypto.spec.PBEKeySpec.<init> (PBEKeySpec.java:115)
  at com.google.android.vending.licensing.AESObfuscator.<init> (AESObfuscator.java:59)
  at com.google.android.vending.expansion.downloader.impl.DownloaderService$LVLRunnable.run (DownloaderService.java:730)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:235)
  at android.app.ActivityThread.main (ActivityThread.java:6760)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:911)

Also, would it be possible to update the example to make it compatible with androix and gradle:4.0.0 ?

Thank you and congratulations for this work which makes the use of apk much easier!

**Comment by FalsinSoft** [comment] 2020-08-09 08:05
Hi

Regarding gradle, cause the example is made with Qt, we have to follow the specification of Qt package template file that currently is fixed to version 3.6.0. Move to a newer version not yet "approved" can be risky since, in case of problem, you can't ask support to Qt team or open bug report.

Regarding the error it seem to come from the third party library derived by google official library (check the help for additional explanation) where I have no knowledge of what it does exactly. This NullPointerException error happen sometimes, frequently or is reproducible?

**Comment by FalsinSoft** [comment] 2020-09-24 21:30
Hi

Just update the library for support androidx package. If you still have the problem you can try the latest committed version just for verify.

**Comment by FranckRICHARD01** [comment] 2020-09-24 22:55
I will submit my modified application in the next few days. I will keep 
you informed ...

During the compilation, I have the following warnings :


WARNING: META-INF/androidx.arch.core_core-runtime.version not protected 
by signature. Unauthorized modifications to this JAR entry will not be 
detected. Delete or move the entry outside of META-INF/.
WARNING: 
META-INF/androidx.asynclayoutinflater_asynclayoutinflater.version not 
protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.browser_browser.version not protected by 
signature. Unauthorized modifications to this JAR entry will not be 
detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.coordinatorlayout_coordinatorlayout.version 
not protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.core_core.version not protected by signature. 
Unauthorized modifications to this JAR entry will not be detected. 
Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.cursoradapter_cursoradapter.version not 
protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.customview_customview.version not protected 
by signature. Unauthorized modifications to this JAR entry will not be 
detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.documentfile_documentfile.version not 
protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.drawerlayout_drawerlayout.version not 
protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.fragment_fragment.version not protected by 
signature. Unauthorized modifications to this JAR entry will not be 
detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.interpolator_interpolator.version not 
protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.legacy_legacy-support-core-ui.version not 
protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.legacy_legacy-support-core-utils.version not 
protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.lifecycle_lifecycle-livedata-core.version not 
protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.lifecycle_lifecycle-livedata.version not 
protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.lifecycle_lifecycle-runtime.version not 
protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.lifecycle_lifecycle-viewmodel.version not 
protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.loader_loader.version not protected by 
signature. Unauthorized modifications to this JAR entry will not be 
detected. Delete or move the entry outside of META-INF/.
WARNING: 
META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version 
not protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.print_print.version not protected by 
signature. Unauthorized modifications to this JAR entry will not be 
detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.slidingpanelayout_slidingpanelayout.version 
not protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.swiperefreshlayout_swiperefreshlayout.version 
not protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: 
META-INF/androidx.versionedparcelable_versionedparcelable.version not 
protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.viewpager_viewpager.version not protected by 
signature. Unauthorized modifications to this JAR entry will not be 
detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/services/com.fasterxml.jackson.core.JsonFactory not 
protected by signature. Unauthorized modifications to this JAR entry 
will not be detected. Delete or move the entry outside of META-INF/.

the warnings in androidx*, I can remove them with the directive

  excludes 'META-INF/androix'.

But exclude 'META-INF/services/*' does not work to remove the warning 
about com.fasterxml.jackson.core.JsonFactory

Do I proceed correctly?

Franck

**Comment by FalsinSoft** [comment] 2020-09-25 16:07
To be honest I'm quite to androidx too. Migration steps are explained [here](https://developer.android.com/jetpack/androidx/migrate), I guess these error came from the Jetifier plugin who try to convert all the jar file to androidx than, teorically, should be ok but I'm not very sure about it...

**Comment by FranckRICHARD01** [comment] 2020-09-29 08:49
Hi FalsinSoft !

In fact, the problem comes that the value mSalt == null when the LVLRunner function tries to create an EASObfuscator object.

The problem seems to be mentioned here: https://github.com/auxility/better-apk-expansion/issues/11

Couldn't we do a test on mSalt to avoid a crash?

**Comment by FalsinSoft** [comment] 2020-09-29 20:49
Just committed the changes from the forked project you linked. Please note the requirement of the additional permission android.permission.FOREGROUND_SERVICE for have the updated code work as expected.

**Comment by FranckRICHARD01** [comment] 2020-09-29 21:49
I have just implemented the changes. I will keep you informed of what I see happening...

**Comment by FranckRICHARD01** [comment] 2020-10-09 09:37
The last change you proposed seems to work. I no longer have any java.lang.NullPointerException .

But I also added a test on mSalt in the LVLRunner function. I don't know if this also has an effect ...

Have a nice day!

**Comment by FalsinSoft** [comment] 2020-10-09 16:23
Good news. Please share here your additions if you think could be useful, I'll integrate into the library.

**Comment by FalsinSoft** [comment] 2020-10-15 19:57
Hi
If you think is not necessary to share your changes close this issue if you think the problem is solved.
Thank you

**Closed as completed** 2020-11-28 11:06 UTC
